"""Make the app's icon fonts from Material Symbols Rounded (Apache-2.0).

React Native can't set a variable font's FILL axis, so this cuts two static
fonts, outlined and filled (weight 400, optical size 24), keeps only the icons
in icons.txt, and writes src/ui/icon-codes.ts (name -> character).

  python3 -m pip install fonttools
  python3 scripts/build-icons.py <MaterialSymbolsRounded[FILL,GRAD,opsz,wght].ttf> <….codepoints>
"""
import re, sys
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont
from fontTools.subset import Subsetter, Options

here = Path(__file__).resolve().parent
root = here.parent
ttf, cps = sys.argv[1], sys.argv[2]
codes = dict(line.split() for line in Path(cps).read_text().splitlines() if line.strip())
names = sorted({n for line in (here / 'icons.txt').read_text().splitlines() if not line.startswith('#') for n in line.split()})
missing = [n for n in names if n not in codes]
if missing:
    sys.exit(f'Not in Material Symbols: {", ".join(missing)}')
unicodes = [int(codes[n], 16) for n in names]
for fill, out in ((0, 'KovaSymbols.ttf'), (1, 'KovaSymbolsFilled.ttf')):
    f = instantiateVariableFont(TTFont(ttf), {'FILL': fill, 'wght': 400, 'GRAD': 0, 'opsz': 24})
    o = Options(); o.layout_features = []; o.name_IDs = ['*']; o.notdef_outline = True
    s = Subsetter(o); s.populate(unicodes=unicodes); s.subset(f)
    family = out[:-4]
    for rec in f['name'].names:
        if rec.nameID in (1, 4, 6, 16):
            rec.string = family
    f.save(root / 'assets' / 'fonts' / out)
lines = ',\n'.join(f"  {n}: '\\u{codes[n]}'" if len(codes[n]) <= 4 else f"  {n}: '\\u{{{codes[n]}}}'" for n in names)
(root / 'src' / 'ui' / 'icon-codes.ts').write_text(
    '// Generated by scripts/build-icons.py from Material Symbols Rounded. Do not edit.\n'
    f'export const ICON_CODES: Record<string, string> = {{\n{lines},\n}};\n')
print(f'{len(names)} icons')
